# Generated by Django 3.0.5 on 2021-03-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('reviewerID', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('reviewerName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('asin', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='items')),
                ('brand', models.TextField()),
                ('category', models.TextField()),
                ('category_rank', models.TextField()),
                ('description', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.TextField()),
                ('verified', models.TextField()),
                ('reviewTime', models.DateTimeField()),
                ('reviewText', models.TextField()),
                ('summary', models.TextField()),
                ('vote', models.TextField()),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_recommend.Items')),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_recommend.Customers')),
            ],
        ),
    ]
