# Generated by Django 3.0.5 on 2021-03-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='item_default.jpg', upload_to='items'),
        ),
    ]
