# Generated by Django 3.0.5 on 2021-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0002_auto_20210319_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='brand',
            field=models.TextField(default='No Brand'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.TextField(default='No Category'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category_rank',
            field=models.TextField(default='No Category Rank'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.TextField(default='No Price'),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.TextField(default='No Title'),
        ),
    ]
