# Generated by Django 3.0.5 on 2021-03-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0003_auto_20210319_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='brand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='category_rank',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.TextField(),
        ),
    ]
