# Generated by Django 3.0.5 on 2021-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0005_item_recommendations_user_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_recommendations',
            old_name='asinID',
            new_name='asin',
        ),
    ]
