# Generated by Django 3.0.5 on 2021-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0006_auto_20210427_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='overall',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
