# Generated by Django 3.0.5 on 2021-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0007_auto_20210429_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='reviewerName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='brand',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='category_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='overall',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='reviewText',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='reviewTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='verified',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='vote',
            field=models.IntegerField(null=True),
        ),
    ]
