# Generated by Django 3.0.5 on 2021-04-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0008_auto_20210429_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_recommend.Items')),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_recommend.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='User_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_recommend.Items')),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_recommend.Customers')),
            ],
        ),
    ]
