# Generated by Django 3.0.5 on 2021-04-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0009_user_cart_user_wish_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_wish_list',
            unique_together={('reviewerID', 'asin')},
        ),
    ]
