# Generated by Django 3.0.5 on 2021-04-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0011_auto_20210430_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Wish_List',
            new_name='User_WishList',
        ),
    ]
