# Generated by Django 3.0.5 on 2021-04-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_recommend', '0012_auto_20210430_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Cart',
        ),
    ]
